const viToEn = {
    "Trang chủ": "Home",
    "Khảo sát": "Survey",
    "Liên hệ": "Contact us",
    "Hoàn thành": "Complete",
    "Điều dũng cảm nhất bạn có thể làm đó là chính mình": "The bravest thing you can be is yourself",
    "Tuổi vị thành niên là một giai đoạn có nhiều biến động, phát triển phức tạp hơn các giai đoạn trước, là sự chính yếu trong quá trình biến đổi từ trạng thái trẻ con thành người lớn. Trong giai đoạn này, trẻ thường xuyên có nhiều biến đổi về tâm sinh lí và chưa có sự định hướng rõ rệt về việc làm và hành vi của bản thân, khiến cho một số trẻ rơi vào tình trạng khủng hoảng tâm lí và có những hành vi nông nổi gây ảnh hưởng đến người khác.": "Adolescence is a period of more volatility, more complex development than the previous stages, is the main process of transformation from a child to an adult. During this period, children often have many psychological changes and do not have a clear orientation on their behavior, causing some children to fall into psychological crisis and have immature behavior that affects others.",
    "Ở tuổi vị thành niên thường xuyên xảy ra những rối loạn về tâm lí, rối loạn lo âu, rối loạn hành vi chống đối xã hội,.. Trong đó, Chứng rối loạn thách thức đối lập ảnh hưởng từ 1 - 11% dân số trẻ em nói chung trên toàn thế giới (theo nghiên của DSM-V), và ảnh hưởng nặng nhất đến trẻ vị thành niên – những đối tượng có sự thay đổi về tâm sinh lí rõ rệt nhất. Website này được tạo ra nhằm mục đích khảo sát mức độ dựa trên các câu hỏi dưới hình thức trắc nghiệm và đưa ra lời khuyên cho những trẻ em đang trong độ tuổi vị thành niên có nguy cơ mắc Chứng rối loạn thách thức đối lập.": "In adolescents, there are often psychological disorders: anxiety disorders, antisocial behavioral disorders. In particular, the Oppositional Defiant Disorder, known as ODD, affects 1 - 11% of the young population (according to DSM-V), especially in adolescents - the subjects with the most pronounced physiological changes. This website was created for the purpose of examining the level of based on the questions in the form of multiple-choice questions and giving advice to adolescents who are at risk of Oppositional Defiant Disorder.",
    "Rất thấp": "Very low",
    "Kết quả cho thấy bạn không có những dấu hiệu của Chứng rối loạn thách thức đối lập. Bạn nên tiếp tục quan tâm đến bản thân mình hơn. Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi!": "The results show that you have no symptoms of Oppositional Defiant Disorder. You should continue to care about yourself more. Thank you for participating in our survey!",
    "Thấp": "Low",
    "Kết quả cho thấy những dấu hiệu của Chứng rối loạn thách thức đối lập ở bạn chưa biểu hiện rõ. Bạn nên tiếp tục theo dõi và quan tâm tới bản thân mình. Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi!": "The results show that the signs of your Oppositional Defiant Disorder are not well cleared. You should continue to follow and care about yourself. Thank you for participating in our survey!",
    "Trung bình": "Medium",
    "Kết quả cho thấy Chứng rối loạn thách thức đối lập ở bạn đang có dấu hiệu phát triển. Lúc này, bạn nên dành nhiều thời gian để quan tâm hơn đến bản thân mình. Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi!": "The results show that your Oppositional Defiant Disorder is starting to have signs of development. At this time, you should spend more time to care about yourself. Thank you for participating in our survey!",
    "Cao": "High",
    "Kết quả cho thấy những biểu hiện của Chứng rối loạn thách thức đối lập ở bạn đang phát triển rõ rệt. Bạn cần phải được tư vấn và tìm sự giúp đỡ từ người lớn và các chuyên gia tâm lí. Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi!": "The results show that your symptoms of the Oppositional Defiant Disorder are developing significantly. You should be consulted and find help from adults and psychologists. Thank you for participating in our survey!",
    "Rất cao": "Very high",
    "Kết quả cho thấy bạn đã bị mắc Chứng rối loạn thách thức đối lập ở mức độ nặng và hành vi có thể gây ảnh hưởng xấu đến những người xung quanh. Bạn cần phải được tưu vấn và có sự hỗ trợ kịp thời từ các chuyên gia tâm lí. Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi!": "The results show that you have a severe degree of oppositional challenge disorder and the behavior can affect to everybody. You should be consulted and get prompt support from psychologists. Thank you for participating in our survey!",
    "Kết quả của bạn là:": "Your result is:",
    "Họ và tên": "Name",
    "Giới tính": "Sex",
    "Nam": "Male",
    "Nữ": "Female",
    "Tuổi": "Age",
    "Trường": "School",
    "Nơi cư trú": "Residence",
    "Thành phố": "City",
    "Thị trấn": "Town",
    "Nông thôn": "Countryside",
    "Dân tộc": "Ethnic",
    "Kinh": "Kinh",
    "Thiểu số": "Minority",
    "Bạn là con thứ mấy trong gia đình? (Bạn vui lòng chỉ ghi bằng số: 1, 2, 3,... VD: 1)": "What number are you in your family? (Please enter the number: 1, 2, 3,... Ex: 1)",
    "Tình trạng hôn nhân của bố mẹ": "Marital status of your parents",
    "Bình thường": "Normal",
    "Ly thân": "Separated",
    "Ly dị": "Divorced",
    "Mồ côi": "Orphaned",
    "Lấy ý kiến": "Answer",
    "Không bao giờ": "Never",
    "Hiếm khi": "Rarely",
    "Thỉnh thoảng": "Sometimes",
    "Thường xuyên": "Regularly",
    "Rất thường xuyên": "Always",
    "Bạn hay đổ lỗi cho người khác về lỗi lầm, hành vi sai trái của mình.": "You often blame others for your mistakes and wrongdoing.",
    "Bạn hay tranh cãi, không tuân theo người khác.": "You often argue and not obeying others.",
    "Bạn có những hành động mang tính thách thức, từ chối làm theo quy tắc.": "You have challenging actions, refusing to follow the rules.",
    "Bạn tức giận, không nghe theo lời người lớn.": "You angry, do not listen to adults.",
    "Bạn nói dối người khác.": "You lie to others.",
    "Bạn chửi thề, sử dụng những ngôn ngữ tục tĩu khi tâm trạng không tốt, ức chế.": "You swear, use obscene language when the mood is not good, inhibited.",
    "Bạn là một người sống khép mình, không cởi mở với người khác.": "You are a self-contained person, not open-mind to others.",
    "Bạn thù hằn lâu, luôn tìm ý định trả thù người khác.": "You hostile for a long time, always seeking to take revenge on others.",
    "Bạn cố ý làm phiền, trêu tức khiến người khác khó chịu.": "You deliberately annoy, tease to make others uncomfortable.",
    "Bạn bị thầy cô phê bình, khiển trách khi mắc lỗi.": "You are criticized when you make mistakes by teachers.",
    "Bạn bị bố mẹ phê bình, khiển trách khi mắc lỗi.": "You are criticized reprimanded for making mistakes by your parents.",
    "Bạn bị bạn bè phê bình, khiển trách.": "You are criticized by friends.",
    "Bạn bị người khác đổ lỗi.": "You are being blamed by others.",
    "Bạn dễ tự ái, phật ý với những việc không vừa lòng.": "You are easy to be narcissistic and dissatisfied with things you do not like.",
    "Bạn thấy mặc cảm, tự ti về bản thân.": "You feel inferiority about yourself.",
    "Bạn cảm thấy tủi thân, uất ức khi bị kì thị, xa lánh": "You feel hurt and grievance when discriminated against.",
    "Bạn cảm thấy khó chịu khi cha mẹ không tin tưởng, kiểm soát quá mức.": "You feel uncomfortable when parents do not trust, control you too much.",
    "Bạn cảm thấy tổn thương, sợ hãi khi bị bạo hành tại gia đình.": "You feel hurt and scared when being abused at home.",
    "Bạn thấy tổn thương, sợ hãi khi bị bạo hành tại trường học, ngoài xã hội.": "You feel hurt, scared when being violent in school and in society.",
    "Bạn muốn tự hủy hoại, gây thương tích cho bản thân.": "You want to ruin or hurt yourself.",
    "Bạn đã từng hủy hoại, gây thương tích cho bản thân.": "You have been ruining or hurting yourself.",
    "Bạn muốn gây thương tích cho động vật, con người.": "You want to injure animals and humans.",
    "Bạn đã từng có hành vi tàn bạo, độc ác cho động vật, con người.": "You had cruel acts for animals and humans.",
    "Bạn cảm thấy tức giận với thế giới.": "You feel angry with the world.",
    "Bạn muốn nổi loạn, vi phạm pháp luật như cố tình đốt cháy, phá hoại, ăn cắp...": "You want to rebel, violate laws like: intentionally burning, sabotaging, stealing...",
    "Bạn đã từng có các hành vi vi phạm pháp luật như cố tình đốt cháy, phá hoại, ăn cắp...": "You have committed violations of law such as intentionally burning, vandalizing, stealing...",
    "Cha mẹ bạn mất niềm tin vào con cái.": "Your parents do not trust in their children.",
    "Cha mẹ bạn không dành thời gian để tâm sự, chia sẻ với con.": "Your parents do not spend more time to talk and share with their children.",
    "Cha mẹ không khích lệ, tán thưởng những thành tích tốt mà con đạt được.": "Parents do not encourage and appreciate the good result their children achieved.",
    "Thầy cô không tạo điều kiện để học sinh  phát triển tài năng của bản thân.": "Teachers do not facilitate for students to develop their talents.",
    "Thầy cô không tin tưởng khi giao nhiệm vụ cho học sinh.": "Teachers do not believe in assigning tasks to students.",
    "Bạn bè cùa bạn không đoàn kết, giúp đỡ nhau trong học tập, cuộc sống.": "Your friends do not unite, help each other in study and life.",
    "Bạn bị bạn bè xúc phạm nhân phẩm, danh dự.": "You are offended dignity by your friends.",
    "Bạn bị bạn bè đố kị, ganh ghét.": "You are envioused by friends.",
    "Mọi người không nhìn nhận được khả năng, sự đóng góp của bạn đối với xã hội.": "People do not recognize your ability and your contribution to society.",
    "Bạn bị mọi người  soi mói, chỉ trích.": "You are scrutinized and criticized by people.",
    "Bạn bị kì thị, xa lánh, phân biệt trong cộng đồng.": "You are discriminated against, alienated in the community.",
    "Bạn không muốn chia sẻ những tâm tư, nguyện vọng của bản thân với người khác.": "You do not want to share your opinions and aspirations with others.",
    "Bạn nhạy cảm, dễ bị tác động bởi những yếu tố bên ngoài.": "You are sensitive and easily affected by external factors.",
    "Bạn mặc cảm, tự ti vì hoàn cảnh gia đình: bố mẹ ly dị, bố (mẹ) đã chết...": "You are inferiority because of family circumstances: divorced parents, deceased father (mother)...",
    "Bạn mặc cảm, tự ti vì hoàn cảnh gia đình kinh tế khó khăn.": "You are self-deprecating because of difficult economic family circumstances.",
    "Bạn bị kích động do hay xem các hình ảnh, video, game có nội dung bạo lực.": "You often watch violent images, videos, games.",
    "Bạn mong muốn mình trở nên có trách nhiệm hơn bản thân.": "You want to be more responsible for yourself.",
    "Bạn muốn nói lời xin lỗi sau mỗi lần tranh cãi, không nghe lời cha mẹ.": "You want to apologize after each argument and not obey to your parents.",
    "Bạn muốn người khác thấu hiểu, tôn trọng mình.": "You want others to understand and respect you.",
    "Bạn muốn bản thân mình trở nên bản lĩnh, bình tĩnh giải quyết mọi tình huống.": "You want to be more bravery and calmly handle all situations.",
    "Bạn muốn được bày tỏ quan điểm, ý kiến cá nhân của mình với mọi người.": "You want to express your opinion to everyone.",
    "Bạn muốn cha mẹ dành thời gian để quan tâm, chia sẻ với con cái.": "You want your parents spend more time to take care and share with their children.",
    "Bạn mong muốn được chia sẻ những khúc mắc, vấn đề khó khăn với thầy cô.": "You want to share difficulty and problems with teachers.",
    "Bạn mong muốn thầy cô không quá kì vọng vào thành tích học tập của bạn.": "You want teachers to not expect too much in your academic achievements.",
    "Bạn mong muốn được thầy cô ủng hộ, tạo điều kiện để phát triển tài năng của bạn.": "You want to be supported and enabled to develop your talents from your teachers.",
    "Bạn muốn chia sẻ những niềm vui, nỗi buồn với bạn bè. ": "You want to share the joys and sorrows with friends.",
    "Bạn mong muốn được bạn bè tôn trọng.": "You want to be respected by your friends.",
    "Bạn mong muốn xã hội nhìn nhận khả năng, sự cống hiến của bạn.": "You want society to recognize your ability and your dedication.",
    "Bạn muốn được tham gia vào các hoạt động công ích của xã hội.": "You want to be involved in the society's activities."
}
export default function translate(lan, data) {
    if (lan === "vi") {
        return data
    }
    return viToEn[data]
}